# Generated by Django 5.0.3 on 2024-04-05 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_alter_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
