# Generated by Django 5.0.3 on 2024-04-07 08:43

import gallery_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0008_alter_album_cover_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(max_length=1000, upload_to=gallery_app.models.new_file_name),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=gallery_app.models.new_file_name),
        ),
    ]
